# Generated by Django 4.2.17 on 2025-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0003_auto_20180709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/2ddd1a64f7304953997a53298450b6b3', verbose_name='系统用户头像'),
        ),
        migrations.AlterField(
            model_name='sysuserthemenumodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
