# Generated by Django 4.2.17 on 2025-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingSet', '0018_auto_20180709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/e1a05b1646a94d55be3aad9582257085', verbose_name='分享图片'),
        ),
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='set_path',
            field=models.CharField(choices=[('5', '内容页面'), ('2', '发布页面'), ('0', '通用页面'), ('3', '发现页面'), ('1', '活动页面'), ('4', '消息页面')], default='0', max_length=1, verbose_name='分享页面设置'),
        ),
    ]
